spring:
  ai:
    ollama:
      base-url: ${OLLAMA_URL:http://host.docker.internal:11434}
      chat:
        model: ${OLLAMA_MODEL:qwen2.5-coder:3b}

  application:
    name: LocalCoder

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/localcoder}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:localcoder}
    password: ${DB_PASSWORD:localcoder}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    com.localdoc: DEBUG
